# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 02:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 2, 21, 36, 549382, tzinfo=utc)),
        ),
    ]
